version: "3"

services:
 # mysql:
    #image: sameersbn/mysql:5.7.22-1
    #environment:
    #- DB_USER=hesk
    #- DB_PASS=hesk
    #- DB_NAME=hesk
    #volumes:
 #   - ./volumes/mysql:/var/lib/mysql

  hesk_db:
    image: mariadb:10.5
    environment:
    - MARIADB_USER=hesk
    - MARIADB_PASSWORD=heskpassword
    - MARIADB_DATABASE=hesk
    - MARIADB_RANDOM_ROOT_PASSWORD=1
    volumes:
    - ./volumes/mariadb:/var/lib/mysql

  hesk_app:  
    build: ./
    depends_on:
      - hesk_db
    ports:
      - "8091:80"
        #ead_only: true
        #restart: unless-stopped
    volumes:
      # This directory must have cert files if you want to enable SSL
      - ./hesk/:/srv/
      - /etc/localtime:/etc/localtime:ro
